spring.application.name=EvidentaEchipelorSportiveDeStudenti

spring.datasource.url=jdbc:sqlserver://DESKTOP-5LICB3E:1433;databaseName=Evidenta echipeleor sportive de studenti;encrypt=true;trustServerCertificate=true
spring.datasource.username=Cosmin
spring.datasource.password=Cosmin

spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.show-sql=true